In [11]:
import datasets
from datasets import load_dataset
from tqdm import tqdm
import numpy as np

In [9]:
d_ = load_dataset("narrativeqa")
d_

DatasetDict({
    train: Dataset({
        features: ['document', 'question', 'answers'],
        num_rows: 32747
    })
    test: Dataset({
        features: ['document', 'question', 'answers'],
        num_rows: 10557
    })
    validation: Dataset({
        features: ['document', 'question', 'answers'],
        num_rows: 3461
    })
})

In [10]:
d_["train"][0]["answers"]

[{'text': 'the elderly spinster aunt of the Earl de Verseley and Captain Delmar',
  'tokens': ['the',
   'elderly',
   'spinster',
   'aunt',
   'of',
   'the',
   'Earl',
   'de',
   'Verseley',
   'and',
   'Captain',
   'Delmar']},
 {'text': "She's Captail Delmar's aunt.",
  'tokens': ['She', 's', 'Captail', 'Delmar', 's', 'aunt', '.']}]

In [13]:
len_summary = []
len_text = []
len_question = []
len_answer = []

for split in d_:
    for instance in tqdm(d_[split]):
        len_summary.append(instance["document"]["summary"]["text"].split(" ").__len__())
        len_text.append(instance["document"]["text"].split(" ").__len__())
        len_question.append(instance["question"]["text"].split(" ").__len__())
        
        len_ans = 0
        for answer in instance["answers"]:
            len_ans += answer["text"].split(" ").__len__()
        len_ans /= len(instance["answers"])
        len_answer.append(len_ans)

#
for list_ in [len_summary, len_text, len_question, len_answer]:
    print(np.percentile(list_, [0, 25, 50, 75, 90, 100]))

100%|██████████| 3461/3461 [00:17<00:00, 199.93it/s]

[198. 405. 596. 716. 838. 993.]
[  2958.  35466.  77272. 115751. 150600. 386427.]
[   3.    6.    8.   11.   13. 1195.]
[  1.    2.    3.5   6.    8.5 110. ]


In [20]:
d_ = load_dataset("natural_questions")
d_

Downloading: 100%|██████████| 17.3k/17.3k [00:00<00:00, 1.48MB/s]
Downloading:  43%|████▎     | 61.3G/143G [21:35<28:47, 47.3MB/s]


KeyboardInterrupt: 

In [ ]:
d_squad = load_dataset("squad_v2")

In [ ]:
d_squad["train"][1000]